[095] 소스 코드 Ⅱ-28 데이터 읽기

In [1]:
import pandas as pd
import numpy as np
df_notnull = pd.read_csv('/content/Titanic_2.csv')

[095] 소스 코드 Ⅱ-29 데이터 확인하기

In [2]:
df_notnull.head()

,Unnamed: 0,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,0,3,male,22.0,1,0,7.250000,S
1,1,1,1,female,38.0,1,0,19.026803,C
2,2,1,3,female,26.0,0,0,7.925000,S
3,3,1,1,female,35.0,1,0,53.100000,S
4,4,0,3,male,35.0,0,0,8.050000,S

[095] 소스 코드 Ⅱ-30 데이터 전처리하기(데이터의 형태 변경)

In [3]:
o_sex = pd.get_dummies(df_notnull.Sex)
o_embarked = pd.get_dummies(df_notnull.Embarked, prefix = 'town')
df_notnull = pd.concat([df_notnull, o_sex, o_embarked], axis = 1)

[096] 소스 코드 Ⅱ-31 데이터 전처리하기(전처리한 데이터 확인)

In [4]:
df_notnull.head(3)

,Unnamed: 0,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,female,male,town_C,town_Q,town_S
0,0,0,3,male,22.0,1,0,7.250000,S,False,True,False,False,True
1,1,1,1,female,38.0,1,0,19.026803,C,True,False,True,False,False
2,2,1,3,female,26.0,0,0,7.925000,S,True,False,False,False,True

[096] 소스 코드 Ⅱ-32 데이터 전처리하기(불필요한 속성 제거)

In [5]:
df_notnull = df_notnull.drop(['Sex', 'Embarked'], axis = 1)
df_notnull.head(3)

,Unnamed: 0,Survived,Pclass,Age,SibSp,Parch,Fare,female,male,town_C,town_Q,town_S
0,0,0,3,22.0,1,0,7.250000,False,True,False,False,True
1,1,1,1,38.0,1,0,19.026803,True,False,True,False,False
2,2,1,3,26.0,0,0,7.925000,True,False,False,False,True

[097] 소스 코드 Ⅱ-33 데이터 전처리하기(데이터 표현 변경)

In [6]:
df_notnull['Fare'] = df_notnull['Fare'].round(2)
df_notnull.head(3)

,Unnamed: 0,Survived,Pclass,Age,SibSp,Parch,Fare,female,male,town_C,town_Q,town_S
0,0,0,3,22.0,1,0,7.25,False,True,False,False,True
1,1,1,1,38.0,1,0,19.03,True,False,True,False,False
2,2,1,3,26.0,0,0,7.92,True,False,False,False,True

[097] 소스 코드 Ⅱ-34 데이터 전처리하기(종속 변수와 독립 변수 지정)

In [14]:
X = df_notnull.loc[:, 'Pclass':]
y = df_notnull['Survived']

[097] 소스 코드 Ⅱ-35 데이터 전처리하기(데이터 분할과 형태 확인)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)
print('train data 개수:', X_train.shape)
print('test data 개수:', X_test.shape)

train data 개수: (534, 10)
test data 개수: (178, 10)

[098] 소스 코드 Ⅱ-36 모델 생성하기(K-최근접 이웃)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

[098] 소스 코드 Ⅱ-37 모델의 성능 평가하기

In [17]:
from sklearn import metrics
y_pred = knn.predict(X_test)
acc = metrics.accuracy_score(y_test, y_pred)
acc

0.7528089887640449

[098] 소스 코드 Ⅱ-38 최적의 K 값 찾기

In [18]:
k = 10
acc_array = np.zeros(k)
for k in np.arange(1,k+1,1):
    knn = KNeighborsClassifier(n_neighbors = k).fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc
    print('k: ', k, '정확도: ', acc)

k:  1 정확도:  0.7191011235955056
k:  2 정확도:  0.7134831460674157
k:  3 정확도:  0.7415730337078652
k:  4 정확도:  0.7471910112359551
k:  5 정확도:  0.7528089887640449
k:  6 정확도:  0.7415730337078652
k:  7 정확도:  0.7134831460674157
k:  8 정확도:  0.7247191011235955
k:  9 정확도:  0.7191011235955056
k:  10 정확도:  0.7359550561797753

[099] 소스 코드 Ⅱ-39 모델 활용하기

In [19]:
new_data1 = np.array([[3, 22.0, 1, 0, 52.1000, 0, 1, 1, 0, 0]])
new_data1 = pd.DataFrame(new_data1, columns = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'female', 'male', 'town_C', 'town_Q', 'town_S'])
prediction = knn.predict(new_data1)
print('생존 여부', prediction)

생존 여부 [1]

[099] 소스 코드 Ⅱ-40 모델 활용하기

In [20]:
new_data2 = np.array([[3, 55.0, 1, 0, 7.1000, 1, 0, 1, 0, 0]])
new_data2 = pd.DataFrame(new_data2, columns = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'female', 'male', 'town_C', 'town_Q', 'town_S'])
prediction = knn.predict(new_data2)
print('생존 여부', prediction)

생존 여부 [0]